# Generated by Django 5.0.6 on 2024-07-09 08:43

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_blogpost_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
